"""
Seed the TrialsIntel database with realistic mock clinical trial data.
Run: python seed_db.py

Data is illustrative only — not sourced from real trials.
"""
from src.database import init_db, save_trial

MOCK_TRIALS = [
    {
        "nct_id": "NCT04506398",
        "title": "Phase 2 Study of Pembrolizumab Plus Chemotherapy in Advanced NSCLC",
        "summary": "This study evaluates pembrolizumab in combination with carboplatin and paclitaxel as first-line treatment for patients with advanced non-small cell lung cancer. The primary endpoint is progression-free survival.",
        "conditions": "Non-Small Cell Lung Cancer, NSCLC",
        "interventions": "Pembrolizumab, Carboplatin, Paclitaxel",
        "sponsor": "Merck Sharp & Dohme",
        "phase": "PHASE2",
        "drug": "Pembrolizumab",
        "disease": "Non-Small Cell Lung Cancer",
        "mechanism": "PD-1 inhibitor",
    },
    {
        "nct_id": "NCT04195386",
        "title": "Nivolumab and Ipilimumab in Metastatic Melanoma",
        "summary": "A randomized trial comparing nivolumab plus ipilimumab versus nivolumab alone in patients with previously untreated metastatic melanoma. Both drugs target immune checkpoint pathways.",
        "conditions": "Melanoma, Metastatic Melanoma",
        "interventions": "Nivolumab, Ipilimumab",
        "sponsor": "Bristol-Myers Squibb",
        "phase": "PHASE3",
        "drug": "Nivolumab",
        "disease": "Metastatic Melanoma",
        "mechanism": "PD-1 and CTLA-4 inhibitor combination",
    },
    {
        "nct_id": "NCT03820622",
        "title": "Atezolizumab in Triple-Negative Breast Cancer",
        "summary": "This trial investigates atezolizumab combined with nab-paclitaxel in patients with unresectable locally advanced or metastatic triple-negative breast cancer. Biomarker analysis of PD-L1 expression is a key secondary objective.",
        "conditions": "Triple-Negative Breast Cancer, TNBC",
        "interventions": "Atezolizumab, Nab-Paclitaxel",
        "sponsor": "Genentech, Inc.",
        "phase": "PHASE3",
        "drug": "Atezolizumab",
        "disease": "Triple-Negative Breast Cancer",
        "mechanism": "PD-L1 inhibitor",
    },
    {
        "nct_id": "NCT04351022",
        "title": "Venetoclax Plus Azacitidine in Newly Diagnosed AML",
        "summary": "A phase 3 study of venetoclax in combination with azacitidine compared to azacitidine alone in adult patients with newly diagnosed acute myeloid leukemia who are ineligible for intensive chemotherapy.",
        "conditions": "Acute Myeloid Leukemia, AML",
        "interventions": "Venetoclax, Azacitidine",
        "sponsor": "AbbVie",
        "phase": "PHASE3",
        "drug": "Venetoclax",
        "disease": "Acute Myeloid Leukemia",
        "mechanism": "BCL-2 inhibitor",
    },
    {
        "nct_id": "NCT03836326",
        "title": "Olaparib Maintenance in BRCA-Mutated Ovarian Cancer",
        "summary": "A placebo-controlled trial of olaparib as maintenance therapy in patients with newly diagnosed BRCA1/2-mutated advanced ovarian cancer who are in complete or partial response after platinum-based chemotherapy.",
        "conditions": "Ovarian Cancer, BRCA Mutation",
        "interventions": "Olaparib",
        "sponsor": "AstraZeneca",
        "phase": "PHASE3",
        "drug": "Olaparib",
        "disease": "Ovarian Cancer",
        "mechanism": "PARP inhibitor",
    },
    {
        "nct_id": "NCT04191590",
        "title": "Osimertinib in EGFR-Mutated NSCLC After Prior EGFR Therapy",
        "summary": "This study examines osimertinib, a third-generation EGFR tyrosine kinase inhibitor, in patients with EGFR T790M mutation-positive non-small cell lung cancer who have progressed on prior EGFR-targeted therapy.",
        "conditions": "Non-Small Cell Lung Cancer, EGFR Mutation",
        "interventions": "Osimertinib",
        "sponsor": "AstraZeneca",
        "phase": "PHASE2",
        "drug": "Osimertinib",
        "disease": "Non-Small Cell Lung Cancer",
        "mechanism": "Third-generation EGFR tyrosine kinase inhibitor",
    },
    {
        "nct_id": "NCT04280783",
        "title": "Ribociclib Plus Letrozole in HR+ HER2- Advanced Breast Cancer",
        "summary": "A phase 3 randomized study evaluating ribociclib, a CDK4/6 inhibitor, in combination with letrozole versus letrozole alone as first-line treatment in postmenopausal women with hormone receptor-positive, HER2-negative advanced breast cancer.",
        "conditions": "Breast Cancer, HR+ HER2- Breast Cancer",
        "interventions": "Ribociclib, Letrozole",
        "sponsor": "Novartis Pharmaceuticals",
        "phase": "PHASE3",
        "drug": "Ribociclib",
        "disease": "Breast Cancer",
        "mechanism": "CDK4/6 inhibitor",
    },
    {
        "nct_id": "NCT04022044",
        "title": "Selpercatinib in RET-Altered Solid Tumors",
        "summary": "LIBRETTO-001 is a phase 1/2 basket trial of selpercatinib in patients with RET fusion-positive solid tumors including non-small cell lung cancer, thyroid cancer, and other advanced solid tumors with RET alterations.",
        "conditions": "RET Fusion-Positive Tumors, NSCLC, Thyroid Cancer",
        "interventions": "Selpercatinib",
        "sponsor": "Eli Lilly and Company",
        "phase": "PHASE1",
        "drug": "Selpercatinib",
        "disease": "RET Fusion-Positive Solid Tumors",
        "mechanism": "RET kinase inhibitor",
    },
    {
        "nct_id": "NCT03710876",
        "title": "Daratumumab in Newly Diagnosed Multiple Myeloma",
        "summary": "This trial evaluates daratumumab in combination with bortezomib, thalidomide, and dexamethasone as induction therapy in transplant-eligible patients with newly diagnosed multiple myeloma.",
        "conditions": "Multiple Myeloma",
        "interventions": "Daratumumab, Bortezomib, Thalidomide, Dexamethasone",
        "sponsor": "Janssen Research & Development",
        "phase": "PHASE3",
        "drug": "Daratumumab",
        "disease": "Multiple Myeloma",
        "mechanism": "Anti-CD38 monoclonal antibody",
    },
    {
        "nct_id": "NCT04526678",
        "title": "Tislelizumab in Relapsed or Refractory Hodgkin Lymphoma",
        "summary": "A single-arm study of tislelizumab, an anti-PD-1 antibody, in patients with relapsed or refractory classical Hodgkin lymphoma who have failed at least two prior lines of therapy.",
        "conditions": "Hodgkin Lymphoma, Classical Hodgkin Lymphoma",
        "interventions": "Tislelizumab",
        "sponsor": "BeiGene",
        "phase": "PHASE2",
        "drug": "Tislelizumab",
        "disease": "Hodgkin Lymphoma",
        "mechanism": "PD-1 inhibitor",
    },
    {
        "nct_id": "NCT04092231",
        "title": "Dupilumab in Adults with Moderate-to-Severe Atopic Dermatitis",
        "summary": "A randomized double-blind placebo-controlled trial evaluating dupilumab subcutaneous injection every two weeks in adult patients with moderate-to-severe atopic dermatitis inadequately controlled with topical therapies.",
        "conditions": "Atopic Dermatitis, Eczema",
        "interventions": "Dupilumab",
        "sponsor": "Sanofi",
        "phase": "PHASE3",
        "drug": "Dupilumab",
        "disease": "Atopic Dermatitis",
        "mechanism": "IL-4 and IL-13 receptor antagonist",
    },
    {
        "nct_id": "NCT03930680",
        "title": "Secukinumab in Active Ankylosing Spondylitis",
        "summary": "This study evaluates secukinumab, an anti-IL-17A monoclonal antibody, in patients with active ankylosing spondylitis who are naive to biologic therapy. The primary endpoint is ASAS40 response at week 16.",
        "conditions": "Ankylosing Spondylitis, Axial Spondyloarthritis",
        "interventions": "Secukinumab",
        "sponsor": "Novartis Pharmaceuticals",
        "phase": "PHASE3",
        "drug": "Secukinumab",
        "disease": "Ankylosing Spondylitis",
        "mechanism": "IL-17A inhibitor",
    },
    {
        "nct_id": "NCT04123678",
        "title": "Upadacitinib in Moderate-to-Severe Rheumatoid Arthritis",
        "summary": "A phase 3 randomized controlled trial of upadacitinib, a selective JAK1 inhibitor, versus methotrexate in patients with moderate-to-severe rheumatoid arthritis and inadequate response to conventional DMARDs.",
        "conditions": "Rheumatoid Arthritis",
        "interventions": "Upadacitinib",
        "sponsor": "AbbVie",
        "phase": "PHASE3",
        "drug": "Upadacitinib",
        "disease": "Rheumatoid Arthritis",
        "mechanism": "Selective JAK1 inhibitor",
    },
    {
        "nct_id": "NCT03978169",
        "title": "Guselkumab in Moderate-to-Severe Plaque Psoriasis",
        "summary": "VOYAGE-1 is a randomized double-blind trial comparing guselkumab, an IL-23 inhibitor, to adalimumab and placebo in patients with moderate-to-severe plaque psoriasis. Primary endpoint is IGA 0/1 at week 16.",
        "conditions": "Plaque Psoriasis, Psoriasis",
        "interventions": "Guselkumab",
        "sponsor": "Janssen Research & Development",
        "phase": "PHASE3",
        "drug": "Guselkumab",
        "disease": "Plaque Psoriasis",
        "mechanism": "IL-23 inhibitor (anti-p19 subunit)",
    },
    {
        "nct_id": "NCT04210895",
        "title": "Vedolizumab in Moderately to Severely Active Crohn's Disease",
        "summary": "A randomized induction and maintenance trial evaluating vedolizumab, a gut-selective anti-integrin antibody, in patients with moderately to severely active Crohn's disease who have failed TNF antagonist therapy.",
        "conditions": "Crohn's Disease, Inflammatory Bowel Disease",
        "interventions": "Vedolizumab",
        "sponsor": "Takeda",
        "phase": "PHASE3",
        "drug": "Vedolizumab",
        "disease": "Crohn's Disease",
        "mechanism": "Anti-α4β7 integrin antibody",
    },
    {
        "nct_id": "NCT04389541",
        "title": "Ozanimod in Relapsing Multiple Sclerosis",
        "summary": "This trial evaluates ozanimod, a sphingosine 1-phosphate receptor modulator, in patients with relapsing forms of multiple sclerosis. The study compares ozanimod to interferon beta-1a on annualized relapse rate.",
        "conditions": "Multiple Sclerosis, Relapsing-Remitting Multiple Sclerosis",
        "interventions": "Ozanimod",
        "sponsor": "Bristol-Myers Squibb",
        "phase": "PHASE3",
        "drug": "Ozanimod",
        "disease": "Multiple Sclerosis",
        "mechanism": "S1P receptor modulator",
    },
    {
        "nct_id": "NCT03485092",
        "title": "Belimumab in Systemic Lupus Erythematosus with Renal Involvement",
        "summary": "BLISS-LN is a phase 3 trial of belimumab, a BLyS inhibitor, added to standard of care in patients with active lupus nephritis. The primary endpoint is renal response at week 104.",
        "conditions": "Systemic Lupus Erythematosus, Lupus Nephritis",
        "interventions": "Belimumab",
        "sponsor": "GlaxoSmithKline",
        "phase": "PHASE3",
        "drug": "Belimumab",
        "disease": "Systemic Lupus Erythematosus",
        "mechanism": "BLyS/BAFF inhibitor",
    },
    {
        "nct_id": "NCT04467957",
        "title": "Baricitinib in Hospitalized Adults with COVID-19",
        "summary": "A randomized double-blind placebo-controlled trial evaluating baricitinib, a JAK1/2 inhibitor, in hospitalized adults with COVID-19 requiring supplemental oxygen or mechanical ventilation.",
        "conditions": "COVID-19, SARS-CoV-2 Infection",
        "interventions": "Baricitinib",
        "sponsor": "Eli Lilly and Company",
        "phase": "PHASE3",
        "drug": "Baricitinib",
        "disease": "COVID-19",
        "mechanism": "JAK1/2 inhibitor",
    },
    {
        "nct_id": "NCT04313023",
        "title": "Ixekizumab in Active Psoriatic Arthritis",
        "summary": "A phase 3 randomized controlled study of ixekizumab, an IL-17A inhibitor, in biologic-naive patients with active psoriatic arthritis. The trial evaluates ACR20 response, minimal disease activity, and radiographic progression.",
        "conditions": "Psoriatic Arthritis",
        "interventions": "Ixekizumab",
        "sponsor": "Eli Lilly and Company",
        "phase": "PHASE3",
        "drug": "Ixekizumab",
        "disease": "Psoriatic Arthritis",
        "mechanism": "IL-17A inhibitor",
    },
    {
        "nct_id": "NCT04042727",
        "title": "Satralizumab in Neuromyelitis Optica Spectrum Disorder",
        "summary": "SAkuraStar is a randomized double-blind placebo-controlled trial evaluating satralizumab, an IL-6 receptor recycling antibody, as monotherapy in patients with neuromyelitis optica spectrum disorder (NMOSD).",
        "conditions": "Neuromyelitis Optica Spectrum Disorder, NMOSD",
        "interventions": "Satralizumab",
        "sponsor": "Chugai Pharmaceutical",
        "phase": "PHASE3",
        "drug": "Satralizumab",
        "disease": "Neuromyelitis Optica Spectrum Disorder",
        "mechanism": "IL-6 receptor inhibitor",
    },
    {
        "nct_id": "NCT04560153",
        "title": "Erdafitinib in FGFR-Altered Urothelial Carcinoma",
        "summary": "A phase 2 trial of erdafitinib, a pan-FGFR kinase inhibitor, in patients with locally advanced or metastatic urothelial carcinoma with FGFR2 or FGFR3 alterations who progressed after platinum-based chemotherapy.",
        "conditions": "Urothelial Carcinoma, Bladder Cancer",
        "interventions": "Erdafitinib",
        "sponsor": "Janssen Research & Development",
        "phase": "PHASE2",
        "drug": "Erdafitinib",
        "disease": "Urothelial Carcinoma",
        "mechanism": "Pan-FGFR kinase inhibitor",
    },
    {
        "nct_id": "NCT03900221",
        "title": "Capmatinib in MET Exon 14-Skipping NSCLC",
        "summary": "GEOMETRY mono-1 is a phase 2 multicohort study of capmatinib, a MET inhibitor, in patients with MET exon 14-skipping non-small cell lung cancer across treatment-naive and previously treated settings.",
        "conditions": "Non-Small Cell Lung Cancer, MET Exon 14 Skipping",
        "interventions": "Capmatinib",
        "sponsor": "Novartis Pharmaceuticals",
        "phase": "PHASE2",
        "drug": "Capmatinib",
        "disease": "Non-Small Cell Lung Cancer",
        "mechanism": "MET kinase inhibitor",
    },
    {
        "nct_id": "NCT04287244",
        "title": "Pralsetinib in RET Fusion-Positive NSCLC",
        "summary": "ARROW is a phase 1/2 open-label study evaluating pralsetinib in patients with RET fusion-positive non-small cell lung cancer. Cohorts include treatment-naive patients and those previously treated with platinum-based chemotherapy.",
        "conditions": "Non-Small Cell Lung Cancer, RET Fusion",
        "interventions": "Pralsetinib",
        "sponsor": "Blueprint Medicines",
        "phase": "PHASE2",
        "drug": "Pralsetinib",
        "disease": "Non-Small Cell Lung Cancer",
        "mechanism": "Selective RET inhibitor",
    },
    {
        "nct_id": "NCT04164784",
        "title": "Lurbinectedin in Small Cell Lung Cancer After Platinum Failure",
        "summary": "A phase 2 basket trial evaluating lurbinectedin as second-line therapy in patients with small cell lung cancer who progressed on or after platinum-based chemotherapy. Primary endpoint is objective response rate.",
        "conditions": "Small Cell Lung Cancer, SCLC",
        "interventions": "Lurbinectedin",
        "sponsor": "PharmaMar",
        "phase": "PHASE2",
        "drug": "Lurbinectedin",
        "disease": "Small Cell Lung Cancer",
        "mechanism": "RNA polymerase II inhibitor",
    },
    {
        "nct_id": "NCT04471220",
        "title": "Niraparib in BRCA-Mutated Metastatic Castration-Resistant Prostate Cancer",
        "summary": "TRITON3 is a phase 3 trial comparing niraparib, a PARP inhibitor, versus physician's choice (docetaxel or an androgen receptor pathway inhibitor) in patients with BRCA1/2-mutated metastatic castration-resistant prostate cancer.",
        "conditions": "Prostate Cancer, Metastatic Castration-Resistant Prostate Cancer",
        "interventions": "Niraparib",
        "sponsor": "Janssen Research & Development",
        "phase": "PHASE3",
        "drug": "Niraparib",
        "disease": "Prostate Cancer",
        "mechanism": "PARP inhibitor",
    },
]


def main():
    init_db()
    for trial in MOCK_TRIALS:
        save_trial(trial)
    print(f"Seeded {len(MOCK_TRIALS)} mock trials into data/trials.db")
    print("Note: This is illustrative demo data, not sourced from real clinical trial records.")


if __name__ == "__main__":
    main()
